# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.2
loader_version=0.18.6

#Dependencies
fabric_version=0.152.2+26.2
stimuli_version=0.6.1+26.2
player_roles_version=1.10.0
permission_api_version=0.7.0

# Mod Properties
mod_version=0.4.0
maven_group=xyz.nucleoid
archives_base_name=leukocyte
